//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSE.Tunes.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistEntity
    {
        public int InterpretID { get; set; }
        public string Interpret { get; set; }
        public string Interpret_Lang { get; set; }
        public string Guid { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
