//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSE.Tunes.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class filtersettings
    {
        public int filterid { get; set; }
        public int mode { get; set; }
        public string value { get; set; }
        public bool isused { get; set; }
        public string benutzer { get; set; }
    }
}
