//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSE.Tunes.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistEntryEntity
    {
        public int EntryId { get; set; }
        public int PlaylistId { get; set; }
        public int LiedId { get; set; }
        public System.Guid Guid { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<int> sortorder { get; set; }
    }
}
