//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSE.Tunes.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistEntity
    {
        public int ListId { get; set; }
        public string ListName { get; set; }
        public string User { get; set; }
        public string guid { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
