//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSE.Tunes.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TunesEntities : DbContext
    {
        public TunesEntities()
            : base("name=TunesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<filtersettings> filtersettings { get; set; }
        public DbSet<genre> genre { get; set; }
        public DbSet<HistoryEntity> history { get; set; }
        public DbSet<ArtistEntity> interpreten { get; set; }
        public DbSet<TrackEntity> lieder { get; set; }
        public DbSet<medium> medium { get; set; }
        public DbSet<PlaylistEntity> playlist { get; set; }
        public DbSet<PlaylistEntryEntity> playlistentries { get; set; }
        public DbSet<AlbumEntity> titel { get; set; }
    }
}
